# -*- coding: utf-8 -*-
"""station_proj2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BNCtCVMsShfeFg_4BIUiLGCOLTnoS4V
"""

import random

def newRoll():
  a = random.randrange(1,6)
  b = random.randrange(1,6)
  print(f"The sum of dice is {a} + {b} = {a + b}")
  return a,b

a,b = newRoll()
if a + b == 7 or a + b == 11:
  print("You won")
elif a + b == 2 or a + b == 3 or a + b == 12:
  print(f"You lost")
else:
  g = a + b
  print(f"Your goal number is {g}")
  t = True
  while t:
    a,b = newRoll()
    if a + b == 7:
      print("You lost")
      t = False
    elif a + b == g:
      print("You won")
      t = False