# -*- coding: utf-8 -*-
"""station_proj1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjersxzxMDPV1MkA5w20vhXDtY9BoIKP
"""

def Template1():
  number = input("Input a number: ")
  number2 = input("Input a number again: ")
  time_measure = input("Measure of time: ")
  transport = input("Mode of transportation: ")
  adjective = input("Input an adjective: ")
  adjective2 = input("Input an adjective again: ")
  adjective3 = input("Input an adjective again: ")
  color = input("Input a color: ")
  body_part = input("Input a part of the body: ")
  body_part2 = input("Input a part of the body again: ")
  verb = input("Input a verb: ")
  noun = input("Input a noun: ")
  noun2 = input("Input a noun again: ")
  noun3 = input("Input a noun again: ")
  noun4 = input("Input a noun again: ")
  silly_word = input("Input a silly word: ")

  print(f'''It was about {number} {time_measure} ago when I arrived at the hospital in a {transport}.
  The hospital is a/an {adjective} place, there are a lot of {adjective2} {noun}s here.
  There are nurses here who have {color} {body_part}. If someone wants to come into my room I told them that they have to {verb} first.
  I’ve decorated my room with {number2} {noun2}. Today I talked to a doctor and they were wearing a {noun3} on their {body_part2}.
  I heard that all doctors {verb} {noun4} every day for breakfast. The most {adjective3} thing about being in the hospital is the {silly_word} {noun} !''')

def Template2():
  person_name = input("Input a person's name: ")
  noun = input("Input a noun: ")
  noun2 = input("Input a noun again: ")
  adjective_feeling = input("Input an adjective (feeling): ")
  adjective_feeling2 = input("Input an adjective (feeling) again: ")
  verb = input("Input a verb: ")
  verb2 = input("Input a verb again: ")
  animal = input("Input an animal: ")
  color = input("Input a color: ")
  verb_ing = input("Input a verb + ing: ")
  adverb_ly = input("Input an adverb + ly: ")
  number = input("Input a number: ")
  time_measure = input("Measure of time: ")
  silly_word = input("Input a silly word: ")

  print(f'''This weekend I am going camping with {person_name}. I packed my lantern, sleeping bag, and {noun}.
  I am so {adjective_feeling} to {verb} in a tent. I am {adjective_feeling2} we might see a(n) {animal}, I hear they’re kind of dangerous.
  While we’re camping, we are going to hike, fish, and {verb2}. I have heard that the {color} lake is great for {verb_ing}.
  Then we will {adverb_ly} hike through the forest for {number} {time_measure}.
  If I see a {color} {animal} while hiking, I am going to bring it home as a pet! At night we will tell {number} {silly_word} stories and roast {noun2} around the campfire!! ''')

def Template3():
  person_name = input("Input a person's name: ")
  color = input("Input color: ")
  animal = input("Input an animal: ")
  place = input("Input a place: ")
  adjective = input("Input an adjective: ")
  adjective2 = input("Input an adjective again: ")
  adjective3 = input("Input an adjective again: ")
  adjective4 = input("Input an adjective again: ")
  adjective5 = input("Input an adjective again: ")
  magical_creatures = input("Input magical creatures: ")
  magical_creatures2 = input("Input magical creatures again: ")
  room_in_house = input("Input room in a house: ")
  noun = input("Input a noun: ")
  noun2 = input("Input a noun again: ")
  noun3 = input("Input a noun again: ")
  nouns_plural = input("Input nouns: ")
  nouns_plural2 = input("Input nouns: ")
  number = input("Input a number: ")
  time_measure = input("Measure of time: ")
  verb_ing = input("Input verb + ing: ")

  print(f'''Dear {person_name}, I am writing to you from a {adjective} castle in an enchanted forest.
  I found myself here one day after going for a ride on a {color} {animal} in {place}.
  There are {adjective2} {magical_creatures} and {adjective3} {magical_creatures2} here! In the {room_in_house} there is a pool full of {noun}.
  I fall asleep each night on a {noun2} of {nouns_plural} and dream of {adjective4} {nouns_plural2}. It feels as though I have lived here for {number} {time_measure}.
  I hope one day you can visit, although the only way to get here now is {verb_ing} on a {adjective5} {noun3}!!''')

print("Pick a template \n 1.  2.  3.")

template = int(input("Choose template: 1, 2, 3 \n"))
while template != 1 and template != 2 and template != 3 :
  template = int(input("Choose template: 1, 2, 3 \n"))
if template == 1:
  Template1()
elif template == 2:
  Template2()
else:
  Template3()